version: '3.9'
name: ocm
services:

  dimensions-threejs:
    container_name: dimensions-threejs
    build:
      context: ./tools/threejs/
      dockerfile: ./Dockerfile.threejs
  
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./tools/threejs:/usr/share/nginx/html
    ports:
      - 8896:80
